#minikube service membership1-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: membership4-deployment
  labels:
    app: membership4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: membership4
  template:
    metadata:
      labels:
        app: membership4
    spec:
      containers:
        - name: membership4
          image: membership
          ports:
            - name: http
              containerPort: 8084
              protocol: TCP
          env:
            - name: DEBUG_PORT
              value: "4004"
            - name: HOST
              value: "membership4-service.default.svc.cluster.local"
            - name: NODES
              value: "membership1-service.default.svc.cluster.local:8081;membership2-service.default.svc.cluster.local:8082;membership3-service.default.svc.cluster.local:8083;membership4-service.default.svc.cluster.local:8084"
            - name: PORT
              value: "8084"
          imagePullPolicy: Never