#minikube service membership1-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: membership2-deployment
  labels:
    app: membership2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: membership2
  template:
    metadata:
      labels:
        app: membership2
    spec:
      containers:
        - name: membership2
          image: membership
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          env:
            - name: DEBUG_PORT
              value: "4002"
            - name: HOST
              value: "membership2-service.default.svc.cluster.local"
            - name: NODES
              value: "membership1-service.default.svc.cluster.local:8081;membership2-service.default.svc.cluster.local:8082;membership3-service.default.svc.cluster.local:8083;membership4-service.default.svc.cluster.local:8084"
            - name: PORT
              value: "8082"
          imagePullPolicy: Never